# Generated by Django 3.2.7 on 2024-02-15 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0003_auto_20240215_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendanceApp.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendanceApp.designation'),
        ),
    ]
