# Generated by Django 3.2.7 on 2024-02-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0006_alter_leave_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
    ]
